apiVersion: v1
kind: Service
metadata:
  name: backapp
  labels:
    app: backapp
    training: block3
    homework: backapp
spec:
  selector:
      app: backapp
      training: block3
      homework: backapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081